# Configuration file for PotatoCore

# When to automatically send the scheduled message
schedule_timer: "23:22"
# language eg. "zh-cn"
language: "zh-cn"

format:

  prefix:
    console: "[PotatoCore]"
    to-mc: "&aPotatoCore &7> "
    to-qq: "[Core]"