name: PotatoCore
version: '${version}'
main: io.yukonisen.potatocore.PotatoCore
api-version: 1.18
authors: [ yukonisen, dmzz-yyhyy ]
description: PotatoCore for the UnitedPotato
softdepend:
  - MiraiMC
commands:
  ptb:
    description: "PotatoBot main command"
permissions:
  potato.*:
    description: "PotatoCore permission group"
    default: false
    children:
      potato.admin:
        description: "PotatoCore admin"
        default: op