name: Java CI with Maven - Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      #- name: Refactor Version
      #  run: sed -i "s/pjversion/1.1-pre3/g" `grep 1.1-pre3 -rl /home/runner/work/CatSero/CatSero`

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload a Build Target
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "CatSero-Artifact"
          path: target/
